# HTMLTest Configuration for Hugo Collections Demo
# This file configures htmltest for link checking and validation

# Directory to test
Directory: "public"

# Output configuration
LogLevel: 3
Quiet: false

# Skip external links (optional - set to true to skip external link checking)
SkipExternal: false

# Timeout for external links
Timeout: 10s

# Ignore patterns for links to skip
Ignore:
  # Ignore localhost links during development
  - "http://localhost"
  - "https://localhost"

  # Ignore common development patterns
  - "http://127.0.0.1"
  - "https://127.0.0.1"

  # Ignore placeholder links
  - "https://example.org"
  - "https://example.com"

  # Ignore social media links that might be placeholders
  - "https://twitter.com/@"
  - "https://github.com/"
  - "https://linkedin.com/in/"

# Custom status codes to ignore
IgnoreStatusCodes:
  - 403  # Forbidden (common for private repos)
  - 429  # Rate limited

# User agent for requests
UserAgent: "htmltest/1.0"

# Follow redirects
FollowRedirects: true

# Maximum redirects to follow
MaxRedirects: 3
