baseURL = "https://example.org/"
languageCode = "en-us"
title = "Hugo Collections Demo"
disableKinds = ["taxonomy", "term"]

# Pagination settings (Hugo v0.128.0+ format)
[pagination]
  pagerSize = 5
  path = "page"
